# Generated by Django 2.2.5 on 2019-09-24 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allAlbums', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allSongs', models.TextField(default='null')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='null')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Song'),
        ),
    ]
